### ISSUE TITLE
Notification in HASS when no data

### ISSUE THREAD

**Issue by leejoow** [cyberjunky/RTL-SDR-P2000Receiver-HA#29]
Not a real issue, but more of a question. 

@Dinges28  wrote in a pull request he lets HASS send a message if there is no update in the last 30 minutes. I'm trying to get this done, but I cannot figure it out. 

Do you have an example how to get this working?

**Comment by Dinges28** [comment]
I have it right now as a automation in Home Assistant for the sensor that display's most of the country....

```
- id: '4000000000012'
  alias: SDR hangt Notification
  trigger:
    - platform: state
      entity_id: sensor.p2000sdr
      for:
        minutes: 30
  action:
  - service: persistent_notification.create
    data_template:
      title: P2000SDR hangt
      message: "P2000SDR hangt"
  - service: notify.mobile_app_ios
    data_template:
      title: P2000SDR hangt
      message: P2000SDR hangt - {{ now().strftime("%d-%m-%Y - %H:%M:%S") }}
```


Bit I would like to have a dummy sensor that just updates on every message that is received and trigger this automation on that sensor (ultimate would be a script that logs in to the machine and restarts the service ;-) )
